- hosts: webserver
  tasks:
   - name: creating a directory
     file:
       state: directory
       path: "/dvd1"
   - name: mount dvd
     mount:
       src: "/dev/cdrom"
       path: "/dvd1"
       state: mounted
       fstype: "iso9660"
   - name: yum appstream
     yum_repository:
       baseurl: "/dvd1/AppStream"
       name: "dvd1"
       description: "yum repo dvd1"
       gpgcheck: no
   - name: yum baseOS
     yum_repository:
       baseurl: "/dvd1/BaseOS"
       name: "dvd2"
       description: "yum repo dvd2"
       gpgcheck: no   
   - name: install httpd server
     package:
       name: httpd
       state: present
   - name: install php
     package:
       name: php
       state: present
   - name: copy html file
     copy:
       src: /root/task12_1/index.php
       dest: /var/www/html/
  
   - name: starting httpd service
     service:
       name: httpd
       state: started
       enabled: yes

   - name: adding firewall rule
     firewalld:
       port: "80/tcp"
       state: enabled
       permanent: true
       immediate: true

- hosts: loadbalancer
  tasks:
   - name: install HAproxy
     package:
       name: haproxy
       state: present
   - name: configuring HAproxy
     template:
       dest: "/etc/haproxy/haproxy.cfg"
       src: "/root/task12_1/haproxy.cfg.j2"
   - name: starting HAproxy service
     service:
       name: haproxy
       state: restarted
